name: sync-ssh
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: sync.ssh cli helps to keep sync your important files/dir in github.
description: sync.ssh is the faster syncing powerful tool, which helps us to keep maintain our file and dir backup!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  sync:
    command: bin/sync
    plugs:
      - home

parts:
  woke:
    plugin: go
    source-type: git
    source: https://github.com/meanii/sync.ssh